---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.0
    exclude: ^(data-.*|tags/)
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-tabs
        args: [--whitespaces-count, '2']

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.13.0
    hooks:
      - id: markdownlint
        name: Markdown Lint
        entry: markdownlint
        language: system
        args:
          - "--config=.markdownlint.json"
          - "--ignore-path=.markdownlintignore"
        types: [markdown]

  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.13.7
    hooks:
      - id: markdown-link-check
        files: \.md$

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        name: YAML Lint
        entry: yamllint
        language: system
        args:
          - "--config-file=.yamllint.yml"
        types: [yaml]
